# install with conda env create -f environment.yml
name: "airbnb"
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - python==3.10
  - matplotlib>=3.7.2
  - scikit-learn>=1.3.0
  - pandas>=2.0.3
  - requests>=2.24.0
  - python-graphviz
  - jinja2
  - lightgbm
  - pip>=23.2.1
  - lifelines>=0.27.7
  - numpy
  - XGBoost
  - shap
  - seaborn
  - pip:
      - graphviz
      - mglearn
      - psutil>=5.7.2
